// <auto-generated />
using System;
using FilRouge.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilRouge.Migrations
{
    [DbContext(typeof(FilRougeContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FilRouge.Models.Commentaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contenu");

                    b.Property<byte[]>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("TacheId")
                        .HasColumnType("INT")
                        .HasColumnName("tache_id");

                    b.HasKey("Id");

                    b.HasIndex("TacheId");

                    b.ToTable("Commentaire", (string)null);
                });

            modelBuilder.Entity("FilRouge.Models.Liste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("nom");

                    b.Property<int?>("ProjetId")
                        .HasColumnType("INT")
                        .HasColumnName("projet_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId");

                    b.ToTable("Liste", (string)null);
                });

            modelBuilder.Entity("FilRouge.Models.Projet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("nom");

                    b.HasKey("Id");

                    b.ToTable("Projet", (string)null);
                });

            modelBuilder.Entity("FilRouge.Models.Tache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("EndDate")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("endDate");

                    b.Property<int?>("ListeId")
                        .HasColumnType("INT")
                        .HasColumnName("liste_id");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("nom");

                    b.HasKey("Id");

                    b.HasIndex("ListeId");

                    b.ToTable("Tache", (string)null);
                });

            modelBuilder.Entity("FilRouge.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("nom");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("FilRouge.Models.Commentaire", b =>
                {
                    b.HasOne("FilRouge.Models.Tache", "Tache")
                        .WithMany("Commentaires")
                        .HasForeignKey("TacheId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Tache");
                });

            modelBuilder.Entity("FilRouge.Models.Liste", b =>
                {
                    b.HasOne("FilRouge.Models.Projet", "Projet")
                        .WithMany("Listes")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("FilRouge.Models.Tache", b =>
                {
                    b.HasOne("FilRouge.Models.Liste", "Liste")
                        .WithMany("Taches")
                        .HasForeignKey("ListeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Liste");
                });

            modelBuilder.Entity("FilRouge.Models.Liste", b =>
                {
                    b.Navigation("Taches");
                });

            modelBuilder.Entity("FilRouge.Models.Projet", b =>
                {
                    b.Navigation("Listes");
                });

            modelBuilder.Entity("FilRouge.Models.Tache", b =>
                {
                    b.Navigation("Commentaires");
                });
#pragma warning restore 612, 618
        }
    }
}
